### ISSUE TITLE
How to temporally agregate SI & TI values?

### ISSUE THREAD

**Issue by Qub3k** [VQEG/siti-tools#22]
The [README.md](https://github.com/VQEG/siti-tools/blob/main/README.md) file suggests that maximum values of both per-frame SI & per-frame TI should be used to represent the overall SI & TI values of a scene. However, when I refer to [ITU-T Rec. P.910 (07/22)](https://www.itu.int/rec/T-REC-P.910-202207-S), clause 6.3.4 "Aggregation of SI/TI scores" claims that I should rather use the average to aggregate per-frame TI & SI scores.

So what temporal aggregation method is recommended in the end—taking the maximum per-frame value or averaging per-frame values?

**Comment by slhck** [comment]
The README actually is citing an old version of P.910. We recommended using averages as a better approximate for overall complexity, since the max is prone to outliers.

Some more background on aggregations here: Robitza, W., Rao Ramachandra Rao, R., Göring, S., & Raake, A. (2021). Impact of spatial and temporal information on video quality and compressibility. 2021 13th International Conference on Quality of Multimedia Experience, QoMEX 2021, 65–68.

**Comment by slhck** [comment]
Addressed in 35c83d6
